name: A workflow for my Hello World file
on: 
  push:
    branches:
      [main]
  pull_request: 
    branches: 
      - main
    types: [closed]
      
jobs:
  build:
    if: ${{ github.event.pull_request.merged }}
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Shashnak"
